Default: &defaults
  database: todolist.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: todolist_test.sqlite3
  <<: *defaults

Staging:
  database: todolist_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: todolist_production.sqlite3
  poolsize: 100
  <<: *defaults
